### ISSUE TITLE
Create a webpage for the API

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/places-API#1]
### Why we need this improvement?
In this current version of the page, there is no webpage for the API. 
I've used the default Json-Server webpage to serve the webpage

### How will this change help?
It will enhance the UI of the webpage. It will ensure users to dive into the information related to API. Hence giving a better user-experience. 

### What changes have to be introduced?

**Tasks**
- [ ] Fork the Repository
- [ ] Create a public directory and add your HTML, CSS, JS files
- [ ] Run ``` npm start ``` in the home directory to check if the **public** files are served 

Use the [README](https://github.com/pooranjoyb/places-API/blob/master/README.md) file for reference.
You can use official Json-Server Docs to provide info about the server.

### All the best with your contribution.

**Comment by pooranjoyb** [comment]
### :warning:Make sure you push your master/main branch to the improve-webpage branch. Happy Coding :)

**Comment by varunvarshney00** [comment]
Assign me this issue.

**Comment by pooranjoyb** [comment]
> Assign me this issue.

All the best @varunvarshney00 Go ahead 👍

**Comment by DANIE0812** [comment]
Assign me this issue

**Comment by pooranjoyb** [comment]
Done brother :) @DANIE0812

**Comment by pooranjoyb** [comment]
@DANIE0812 update?

**Comment by varunvarshney00** [comment]
I am sorry but I have tried my best to work on it, but due to unforeseen
circumstances I was not able to work on it. You can unassign this issue.

**Comment by pooranjoyb** [comment]
It's fine someone else is working on it. @varunvarshney00
